name: glyphh-runtime-local

services:
  db_runtime:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: glyphh
      POSTGRES_PASSWORD: glyphh
      POSTGRES_DB: glyphh_runtime
    ports:
      - "5432:5432"
    volumes:
      - glyphh_runtime_db_data:/var/lib/postgresql/data

volumes:
  glyphh_runtime_db_data:
