"""initial schema

Revision ID: 88d76764e4cb
Revises: 
Create Date: 2026-02-08 14:18:50.983640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '88d76764e4cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('glyphs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('concept_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_glyph_embedding', 'glyphs', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_glyph_org_model', 'glyphs', ['org_id', 'model_id'], unique=False)
    op.create_index('idx_glyph_org_model_created', 'glyphs', ['org_id', 'model_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_glyphs_model_id'), 'glyphs', ['model_id'], unique=False)
    op.create_index(op.f('ix_glyphs_org_id'), 'glyphs', ['org_id'], unique=False)
    op.create_table('model_configs',
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('model_path', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('sdk_version', sa.String(length=50), nullable=True),
    sa.Column('meta_name', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.String(length=200), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('encoder_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('similarity_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('beam_width', sa.Integer(), nullable=True),
    sa.Column('max_tree_depth', sa.Integer(), nullable=True),
    sa.Column('resource_quotas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'model_id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_token_org', 'tokens', ['org_id'], unique=False)
    op.create_index('idx_token_org_model', 'tokens', ['org_id', 'model_id'], unique=False)
    op.create_index('idx_token_status', 'tokens', ['status'], unique=False)
    op.create_index(op.f('ix_tokens_model_id'), 'tokens', ['model_id'], unique=False)
    op.create_index(op.f('ix_tokens_org_id'), 'tokens', ['org_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('source_glyph_id', sa.UUID(), nullable=False),
    sa.Column('target_glyph_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_glyph_id'], ['glyphs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_glyph_id'], ['glyphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_glyph_id', 'target_glyph_id', 'edge_type', name='uq_edge_source_target_type')
    )
    op.create_index('idx_edge_org_model', 'edges', ['org_id', 'model_id'], unique=False)
    op.create_index('idx_edge_org_model_type', 'edges', ['org_id', 'model_id', 'edge_type'], unique=False)
    op.create_index('idx_edge_source', 'edges', ['source_glyph_id'], unique=False)
    op.create_index('idx_edge_target', 'edges', ['target_glyph_id'], unique=False)
    op.create_index('idx_edge_type', 'edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_edges_model_id'), 'edges', ['model_id'], unique=False)
    op.create_index(op.f('ix_edges_org_id'), 'edges', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edges_org_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_model_id'), table_name='edges')
    op.drop_index('idx_edge_type', table_name='edges')
    op.drop_index('idx_edge_target', table_name='edges')
    op.drop_index('idx_edge_source', table_name='edges')
    op.drop_index('idx_edge_org_model_type', table_name='edges')
    op.drop_index('idx_edge_org_model', table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_tokens_org_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_model_id'), table_name='tokens')
    op.drop_index('idx_token_status', table_name='tokens')
    op.drop_index('idx_token_org_model', table_name='tokens')
    op.drop_index('idx_token_org', table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_glyphs_org_id'), table_name='glyphs')
    op.drop_index(op.f('ix_glyphs_model_id'), table_name='glyphs')
    op.drop_index('idx_glyph_org_model_created', table_name='glyphs')
    op.drop_index('idx_glyph_org_model', table_name='glyphs')
    op.drop_index('idx_glyph_embedding', table_name='glyphs', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('glyphs')
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###
