"""base

Revision ID: e561b46cf75c
Revises: 
Create Date: 2026-01-29 12:49:43.956541
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e561b46cf75c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_glyphs_name_observed_at'), table_name='glyphs')
    op.create_index('ix_glyphs_name_observed_at', 'glyphs', ['name', sa.literal_column("json_extract_path_text(semantic, 'observed_at')")], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_glyphs_name_observed_at', table_name='glyphs')
    op.create_index(op.f('ix_glyphs_name_observed_at'), 'glyphs', ['name', sa.literal_column("json_extract_path_text(semantic, VARIADIC ARRAY['observed_at'::text])")], unique=False)
    # ### end Alembic commands ###
