"""base

Revision ID: fad8258adff5
Revises: 
Create Date: 2026-01-25 01:55:06.119403
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fad8258adff5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encoders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('roles_config', sa.JSON(), nullable=False),
    sa.Column('vector_dim', sa.Integer(), server_default='1024', nullable=False),
    sa.Column('encoder_seed', sa.Integer(), server_default='42', nullable=False),
    sa.Column('space_id', sa.String(length=64), nullable=False),
    sa.Column('space_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('data_mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('default_encoder_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_space_id'), 'models', ['space_id'], unique=False)
    op.create_table('dashboard_chart_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_chart_configs_model_id'), 'dashboard_chart_configs', ['model_id'], unique=False)
    op.create_index(op.f('ix_dashboard_chart_configs_user_id'), 'dashboard_chart_configs', ['user_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_model_id'), 'edges', ['model_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('glyph_name', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('glyph_name')
    )
    op.create_table('glyph_history_vectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('listener_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('attribute_value', sa.JSON(), nullable=True),
    sa.Column('vector_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glyph_history_vectors_created_at'), 'glyph_history_vectors', ['created_at'], unique=False)
    op.create_index(op.f('ix_glyph_history_vectors_listener_id'), 'glyph_history_vectors', ['listener_id'], unique=False)
    op.create_index(op.f('ix_glyph_history_vectors_model_id'), 'glyph_history_vectors', ['model_id'], unique=False)
    op.create_index(op.f('ix_glyph_history_vectors_role'), 'glyph_history_vectors', ['role'], unique=False)
    op.create_table('glyphs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('semantic', sa.JSON(), nullable=False),
    sa.Column('cortex', postgresql.BYTEA(), nullable=False),
    sa.Column('prediction_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index('ix_glyphs_name_observed_at', 'glyphs', ['name', sa.literal_column("json_extract_path_text(semantic, 'observed_at')")], unique=False)
    op.create_table('model_linguistic_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_linguistic_configs_model_id'), 'model_linguistic_configs', ['model_id'], unique=True)
    op.create_table('model_nl_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_nl_configs_model_id'), 'model_nl_configs', ['model_id'], unique=True)
    op.create_table('model_runtime_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runtime_configs_model_id'), 'model_runtime_configs', ['model_id'], unique=True)
    op.create_table('model_samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_samples_model_id'), 'model_samples', ['model_id'], unique=True)
    op.create_table('model_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('tests', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_tests_model_id'), 'model_tests', ['model_id'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('generated_from_model_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_from_model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_generated_from_model_id'), 'profiles', ['generated_from_model_id'], unique=False)
    op.create_table('trends',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('alpha', sa.Numeric(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trends_model_id'), 'trends', ['model_id'], unique=False)
    op.create_table('glyph_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('vector', postgresql.BYTEA(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('attribute_value', sa.JSON(), nullable=True),
    sa.Column('aligned_to_actual', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trend_definition_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['trend_definition_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glyph_trends_model_id'), 'glyph_trends', ['model_id'], unique=False)
    op.create_index(op.f('ix_glyph_trends_role'), 'glyph_trends', ['role'], unique=False)
    op.create_index(op.f('ix_glyph_trends_timestamp'), 'glyph_trends', ['timestamp'], unique=False)
    op.create_index(op.f('ix_glyph_trends_trend_definition_id'), 'glyph_trends', ['trend_definition_id'], unique=False)
    op.create_table('maps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_profile_id', sa.String(), nullable=False),
    sa.Column('target_profile_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('transformations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['target_profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_source_profile_id'), 'maps', ['source_profile_id'], unique=False)
    op.create_index(op.f('ix_maps_target_profile_id'), 'maps', ['target_profile_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('glyph_name', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('seg_index', sa.Integer(), nullable=False),
    sa.Column('vec', postgresql.BYTEA(), nullable=False),
    sa.ForeignKeyConstraint(['glyph_name'], ['glyphs.name'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'glyph_name', 'layer', 'seg_index', name='uq_segment')
    )
    op.create_index(op.f('ix_segments_model_id'), 'segments', ['model_id'], unique=False)
    op.create_table('trend_charts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trend_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chart_type', sa.String(), nullable=False),
    sa.Column('x_axis', sa.String(), nullable=False),
    sa.Column('y_axes', sa.JSON(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('trail_length', sa.Integer(), nullable=False),
    sa.Column('prediction_steps', sa.Integer(), nullable=False),
    sa.Column('predictions_enabled', sa.Boolean(), nullable=False),
    sa.Column('timeline_marker_color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_charts_trend_id'), 'trend_charts', ['trend_id'], unique=False)
    op.create_table('trend_prediction_frontiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trend_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('last_trend_timestamp', sa.DateTime(), nullable=True),
    sa.Column('frontier_timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('prediction_steps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trend_id', 'role', 'layer', 'segment_index', name='uq_trend_prediction_frontier')
    )
    op.create_index(op.f('ix_trend_prediction_frontiers_trend_id'), 'trend_prediction_frontiers', ['trend_id'], unique=False)
    op.create_table('listeners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('payload_template', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('history_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('map_id', sa.String(), nullable=True),
    sa.Column('throttle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listeners_map_id'), 'listeners', ['map_id'], unique=False)
    op.create_table('map_field_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('map_id', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('target_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_field_mappings_map_id'), 'map_field_mappings', ['map_id'], unique=False)
    op.create_table('model_websocket_listeners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('listener_id', sa.String(), nullable=False),
    sa.Column('concept_type', sa.String(), nullable=False),
    sa.Column('mapper', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_websocket_listeners_listener_id'), 'model_websocket_listeners', ['listener_id'], unique=False)
    op.create_index(op.f('ix_model_websocket_listeners_model_id'), 'model_websocket_listeners', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_websocket_listeners_model_id'), table_name='model_websocket_listeners')
    op.drop_index(op.f('ix_model_websocket_listeners_listener_id'), table_name='model_websocket_listeners')
    op.drop_table('model_websocket_listeners')
    op.drop_index(op.f('ix_map_field_mappings_map_id'), table_name='map_field_mappings')
    op.drop_table('map_field_mappings')
    op.drop_index(op.f('ix_listeners_map_id'), table_name='listeners')
    op.drop_table('listeners')
    op.drop_index(op.f('ix_trend_prediction_frontiers_trend_id'), table_name='trend_prediction_frontiers')
    op.drop_table('trend_prediction_frontiers')
    op.drop_index(op.f('ix_trend_charts_trend_id'), table_name='trend_charts')
    op.drop_table('trend_charts')
    op.drop_index(op.f('ix_segments_model_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_maps_target_profile_id'), table_name='maps')
    op.drop_index(op.f('ix_maps_source_profile_id'), table_name='maps')
    op.drop_table('maps')
    op.drop_index(op.f('ix_glyph_trends_trend_definition_id'), table_name='glyph_trends')
    op.drop_index(op.f('ix_glyph_trends_timestamp'), table_name='glyph_trends')
    op.drop_index(op.f('ix_glyph_trends_role'), table_name='glyph_trends')
    op.drop_index(op.f('ix_glyph_trends_model_id'), table_name='glyph_trends')
    op.drop_table('glyph_trends')
    op.drop_index(op.f('ix_trends_model_id'), table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_profiles_generated_from_model_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_model_tests_model_id'), table_name='model_tests')
    op.drop_table('model_tests')
    op.drop_index(op.f('ix_model_samples_model_id'), table_name='model_samples')
    op.drop_table('model_samples')
    op.drop_index(op.f('ix_model_runtime_configs_model_id'), table_name='model_runtime_configs')
    op.drop_table('model_runtime_configs')
    op.drop_index(op.f('ix_model_nl_configs_model_id'), table_name='model_nl_configs')
    op.drop_table('model_nl_configs')
    op.drop_index(op.f('ix_model_linguistic_configs_model_id'), table_name='model_linguistic_configs')
    op.drop_table('model_linguistic_configs')
    op.drop_index('ix_glyphs_name_observed_at', table_name='glyphs')
    op.drop_table('glyphs')
    op.drop_index(op.f('ix_glyph_history_vectors_role'), table_name='glyph_history_vectors')
    op.drop_index(op.f('ix_glyph_history_vectors_model_id'), table_name='glyph_history_vectors')
    op.drop_index(op.f('ix_glyph_history_vectors_listener_id'), table_name='glyph_history_vectors')
    op.drop_index(op.f('ix_glyph_history_vectors_created_at'), table_name='glyph_history_vectors')
    op.drop_table('glyph_history_vectors')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_edges_model_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_dashboard_chart_configs_user_id'), table_name='dashboard_chart_configs')
    op.drop_index(op.f('ix_dashboard_chart_configs_model_id'), table_name='dashboard_chart_configs')
    op.drop_table('dashboard_chart_configs')
    op.drop_index(op.f('ix_models_space_id'), table_name='models')
    op.drop_table('models')
    op.drop_table('encoders')
    # ### end Alembic commands ###
